KEYBINDS = {
    "open-freeform": "q",
    "closed-freeform": "w",
    "line": "e",
    "circle": "r",
    "rectangle": "t",
    "pan-and-zoom": "a",
    "erase": "s",
    "delete-all": "d",
    "classes": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "alt+1",
        "alt+2",
        "alt+3",
        "alt+4",
        "alt+5",
        "alt+6",
        "alt+7",
        "alt+8",
        "alt+9",
    ],
}

ANNOT_ICONS = {
    "open-freeform": "mdi:draw",
    "closed-freeform": "fluent:draw-shape-20-regular",
    "line": "pepicons-pop:line-y",
    "circle": "gg:shape-circle",
    "rectangle": "gg:shape-square",
    "eraser": "ph:eraser",
    "delete-all": "octicon:trash-24",
    "pan-and-zoom": "el:off",
}

ANNOT_NOTIFICATION_MSGS = {
    "open-freeform": "Open freeform annotation mode",
    "closed-freeform": "Closed freeform annotation mode",
    "line": "Line annotation mode",
    "circle": "Circle annotation mode",
    "rectangle": "Rectangle annotation mode",
    "eraser": "Eraser annotation mode",
    "delete-all": "Delete all annotations",
    "pan-and-zoom": "Pan and zoom mode",
}
