KEYBINDS = {
    "open-freeform": "q",
    "closed-freeform": "w",
    "circle": "e",
    "rectangle": "r",
    # "line": "t",    # todo enable line drawing when #57 is merged
    "pan": "a",
    "erase-annotation": "s",
    "delete-all-annotations": "d",
    "classes": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0",
        "shift+1",
        "shift+2",
        "shift+3",
        "shift+4",
        "shift+5",
        "shift+6",
        "shift+7",
        "shift+8",
        "shift+9",
        "shift+0",
    ],
}
